name: Weekly Equipment Inventory Report

on:
  # Run every Friday at 9:00 AM EST (14:00 UTC during Standard Time, 13:00 UTC during Daylight Time)
  # Using 13:00 UTC to cover both scenarios
  schedule:
    - cron: '0 13 * * 5'  # Friday at 1:00 PM UTC (9:00 AM EST / 8:00 AM EDT)
  
  # Allow manual trigger from Actions tab
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate inventory report
      env:
        LIBCAL_CLIENT_ID: ${{ secrets.LIBCAL_CLIENT_ID }}
        LIBCAL_CLIENT_SECRET: ${{ secrets.LIBCAL_CLIENT_SECRET }}
        LIBCAL_LOCATION_ID: ${{ vars.LIBCAL_LOCATION_ID }}
      run: |
        python generate_inventory.py
    
    - name: Commit and push reports
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add output/
        
        # Only commit if there are changes
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Weekly inventory report - $(date +'%Y-%m-%d')"
          git push
        fi
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: inventory-report-${{ github.run_number }}
        path: output/
        retention-days: 90
